In [1]:
import json
import random

train_file = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/counting_train.json'
val_file = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/counting_val.json'

train_file_new = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/input/counting_train_new.json'
val_file_new = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/input/counting_val_new.json'
test_file_new = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/input/counting_test_new.json'

with open(train_file) as f:
          train_list = json.loads(f.read())

with open(val_file) as f:
          val_list = json.loads(f.read())
          
print("Val List is", len(val_list))
print("Train List is", len(train_list))

('Val List is', 36032)
('Train List is', 324734)


In [2]:
# Custom data last minute
random.Random(5).shuffle(train_list)
train_list_final = train_list[0:288734]
test_list_final = train_list[288734:324734]
val_list_final = val_list

In [3]:
train_file_final = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/input/counting_train_final.json'
val_file_final = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/input/counting_val_final.json'
test_file_final = '/home/ubuntu/efs/amazon-bin/code/workspace/sravan-dl/input/counting_test_final.json'

with open(train_file_final,'wb') as f1:
        json.dump(train_list_final,f1)
        
with open(val_file_final,'wb') as f2:
        json.dump(val_list_final,f2)
        
with open(test_file_final,'wb') as f3:
        json.dump(test_list_final,f3)

In [4]:
# consolidate val and train into a single list
# 156152
#train 109306
#val 31230
# test 15616
data = []
for item in train_list:
    data.append(item)

for item in val_list:
    data.append(item)
    
print("len data is", len(data))

# Prepare training
random.Random(5).shuffle(data)
train_list_new = data[0:109306]
val_list_new = data[109306:140536]
test_list_new = data[140536:156152]

print("len train", len(train_list_new))
print("len val", len(val_list_new))
print("len test", len(test_list_new))

('len data is', 156152)
('len train', 109306)
('len val', 31230)
('len test', 15616)


In [21]:
# Writing all the files to input folder

with open(train_file_new,'wb') as f1:
        json.dump(train_list_new,f1)
        
with open(val_file_new,'wb') as f2:
        json.dump(val_list_new,f2)
        
with open(test_file_new,'wb') as f3:
        json.dump(test_list_new,f3)

In [5]:
import numpy as np
# Checking distribution of training data
train_np = np.zeros(6,)
val_np = np.zeros(6,)
test_np = np.zeros(6,)

for item in train_list_new:
    train_np[item[1]] = train_np[item[1]] + 1
    
for item in test_list_new:
    test_np[item[1]] = test_np[item[1]] + 1
    
for item in val_list_new:
    val_np[item[1]] = val_np[item[1]] + 1
    

In [6]:
print(train_np)
print(test_np)
print(val_np)

[ 2936. 12560. 23321. 27073. 24452. 18964.]
[ 433. 1748. 3374. 3938. 3464. 2659.]
[ 907. 3641. 6635. 7912. 6849. 5286.]
